version: '3.7'

services:
  nginx:
    environment:
      - FQDN=${POSTGRES_PASSWORD:-superset}
    command: /bin/bash -c "mv /etc/nginx/conf.d/superset.conf.mv /etc/nginx/conf.d/superset.conf && envsubst < /etc/nginx/conf.d/superset.conf > /etc/nginx/conf.d/superset.conf && nginx -g 'daemon off;'"
