version: '3.7'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - /etc/letsencrypt/live/${FQDN}/privkey.pem:/etc/nginx/certs/privkey.pem:ro
      - ./nginx:/etc/nginx/superset.conf
      - ./nginx:/etc/nginx/conf.d
    command: /bin/bash -c "mv /etc/nginx/conf.d/superset.conf.mv /etc/nginx/conf.d/superset.conf && envsubst < /etc/nginx/conf.d/superset.conf > /etc/nginx/conf.d/superset.conf && nginx -g 'daemon off;'"
