version: '3.7'

services:
  nginx:
    environment:
      - fqdn=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/superset.conf > /etc/nginx/conf.d/superset.conf && nginx -g 'daemon off;'"
